import img from '@/components/assets/portfolio.png'
import weather from '@/components/assets/weather.png'
import todo from '@/components/assets/Todo.png'
import gas from '@/components/assets/gas.png'

export const projectData = [
  
  {
    img: gas,
    title: "LPG Management System",
    githubLink: "https://github.com/punyakrit/LPG-Portal-MERN-Project",
    deployedLink: "https://lpg-portal-mern-project.vercel.app/",
    skill: ["MERN", "Tailwind CSS","Auth"],
    description:"Introducing an intuitive LPG Management Application powered by the MERN stack. Users can seamlessly create accounts and place orders for LPG services they require. Upon placing an order, users are presented with a detailed checkout bill and seamlessly redirected to a secure payment gateway to complete their transaction. The entire process can be conveniently monitored by admin users, ensuring a smooth and efficient service delivery experience."

  },
  {
    img: img, 
    title: "Portfolio Website",
    githubLink: "https://github.com/punyakrit/portfolio-next",
    deployedLink: "https://www.punyakrit.tech/",
    description: "Welcome to my portfolio website built with Next.js and styled using Tailwind CSS. As a showcase of my skills and projects, this platform reflects my passion for clean design and efficient development. ",
    skill: ["NextJs", "Tailwind CSS"]
  },
  {
    img: weather,
    title: "Weather App",
    githubLink: "https://github.com/punyakrit/Weather-App",
    deployedLink: "https://weather-app-punyakrit.vercel.app/",
    description: "Explore real-time weather information with this intuitive Weather App. Developed with React.js and styled using Tailwind CSS, this application provides accurate weather forecasts using data fetched via Axios from OpenWeather API.",
    skill: ["ReactJs", "Tailwind CSS", "Axios"]

  },

  {
    img: todo,
    title: "Full Stack Todo App",
    githubLink: "https://github.com/punyakrit/FullStack-TodoApp",
    deployedLink: "https://full-stack-todo-app-sable.vercel.app/",
    skill: ["MERN", "Tailwind CSS",],
    description:"A MERN Stack Task Management Application Capable of performing CRUD based Operations and handle requests generated by the User "

  },

  
  
];
