import img from '@/components/assets/portfolio.png'
import weather from '@/components/assets/weather.png'
import todo from '@/components/assets/Todo.png'
import sh from '@/components/assets/sh.png'
import blog from '@/components/assets/blog.png'
import laun from '@/components/assets/laun.png'

export const projectData = [
  
  {
    img: sh,
    title: "Share Hub",
    githubLink: "https://github.com/punyakrit/social-share",
    deployedLink: "https://www.sharehub.xyz/",
    skill: ["NextJs", "Tailwind CSS","NextAuth", "Mongoose"],
    description:"ShareHub is a Project where users can create their public viewable profile containing their customizable social links and important links that they want to share with the world. Also having option to see their page Analytics"

  },
  {
    img: laun,
    title: "SuperDry",
    githubLink: "https://github.com/punyakrit/superdry",
    deployedLink: "https://superdry-kappa.vercel.app/",
    skill: ["NextJs", "Tailwind CSS","NextAuth", "Mongoose"],
    description:"This is a Laundry based website where user can place laundry order and contact and manage their service"

  },
  {
    img: blog,
    title: "Medium Blog Clone",
    githubLink: "https://github.com/punyakrit/medium",
    deployedLink: "https://blog.punyakrit.tech/signup",
    skill: ["ReactJS", "Tailwind CSS","Hono", "PorstgreSQL" ],
    description:"Blogging Allicationusign ReactJs for frontend , Tailwind CSS for styling and Serverless Backend for performing backend compute and PostgreSQL ORM is used for DB. User can create an account and see all the listed blogs and and creat new blogs."

  },
  {
    img: img, 
    title: "Portfolio Website",
    githubLink: "https://github.com/punyakrit/portfolio-next",
    deployedLink: "https://www.punyakrit.tech/",
    description: "Welcome to my portfolio website built with Next.js and styled using Tailwind CSS. As a showcase of my skills and projects, this platform reflects my passion for clean design and efficient development. ",
    skill: ["NextJs", "Tailwind CSS"]
  },
  {
    img: weather,
    title: "Weather App",
    githubLink: "https://github.com/punyakrit/Weather-App",
    deployedLink: "https://weather-app-punyakrit.vercel.app/",
    description: "Explore real-time weather information with this intuitive Weather App. Developed with React.js and styled using Tailwind CSS, this application provides accurate weather forecasts using data fetched via Axios from OpenWeather API.",
    skill: ["ReactJs", "Tailwind CSS", "Axios"]

  },

  {
    img: todo,
    title: "Full Stack Todo App",
    githubLink: "https://github.com/punyakrit/FullStack-TodoApp",
    deployedLink: "https://full-stack-todo-app-sable.vercel.app/",
    skill: ["MERN", "Tailwind CSS",],
    description:"A MERN Stack Task Management Application Capable of performing CRUD based Operations and handle requests generated by the User "

  },

  
  
];
